module.exports = {
  _id: "69931cb3db02afb83c71d346",
  currency: {
    name: "USD",
    symbol: "$",
    countryCode: "US",
    currencyCode: "$",
    isDefault: true,
  },
  privacyPolicyLink: "https://hiko.alkmal.com/privacy-policy",
  termsOfUsePolicyLink: "https://hiko.alkmal.com/terms",
  googlePlayEnabled: false,
  stripeEnabled: false,
  stripePublishableKey: "STRIPE PUBLISHABLE KEY",
  stripeSecretKey: "STRIPE SECRET KEY",
  razorpayEnabled: false,
  razorpayId: "RAZOR PAY ID",
  razorpaySecretKey: "",
  flutterwaveEnabled: false,
  flutterwaveId: "FLUTTER WAVE ID",
  loginBonus: 0,
  isDemoData: false,
  minCoinsToConvert: 1000,
  minCoinsForUserPayout: 1,
  minCoinsForHostPayout: 100,
  minCoinsForAgencyPayout: 10,
  maxFreeChatMessages: 1,
  privateKey: {},
  adminCommissionRate: 20,
  agoraAppCertificate: "ce9a2a19fcc14ed9be64c839f3641833",
  agoraAppId: "d47410e2848749f4b8b0bfb727a27453",
  audioPrivateCallRate: 10,
  chatInteractionRate: 11,
  femaleRandomCallRate: 30,
  generalRandomCallRate: 20,
  isAppEnabled: true,
  maleRandomCallRate: 20,
  videoPrivateCallRate: 10,
  isAutoRefreshEnabled: false,
  cashfreeAndroidEnabled: false,
  cashfreeClientId: "CASHFREE CLIENT ID",
  cashfreeClientSecret: "CASHFREE CLIENT SECRET",
  cashfreeIosEnabled: false,
  paypalAndroidEnabled: false,
  paypalClientId: "PAYPAL CLIENT ID",
  paypalIosEnabled: false,
  paypalSecretKey: "PAYPAL SECRET KEY",
  paystackAndroidEnabled: false,
  paystackIosEnabled: false,
  paystackPublicKey: "PAYSTACK PUBLIC KEY",
  paystackSecretKey: "PAYSTACK SECRET KEY",
  flutterwaveIosEnabled: false,
  googlePayIosEnabled: false,
  razorpayIosEnabled: false,
  stripeIosEnabled: false,
  androidAppLink: "",
  androidAppVersion: "1.0.0",
  iosAppLink: "",
  iosAppVersion: "1.0.0",
};
